/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Desktop
 */
public class TelaMain extends javax.swing.JFrame {

    /**
     * Creates new form TelaMain
     */
    static String tipo;
    public TelaMain(String tipo) {
        initComponents();
        this.tipo = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientecadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        cadastrofornecedor = new javax.swing.JButton();
        cadastroproduto = new javax.swing.JButton();
        consultaproduto = new javax.swing.JButton();
        consultavenda = new javax.swing.JButton();
        RegistoVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clientecadastro.setText("CADASTRAR CLIENTE");
        clientecadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientecadastroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("BEM VINDO USUÁRIO");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        cadastrofornecedor.setText("CADASTRAR FORNECEDOR");
        cadastrofornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrofornecedorActionPerformed(evt);
            }
        });

        cadastroproduto.setText("CADASTRAR PRODUTO");
        cadastroproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroprodutoActionPerformed(evt);
            }
        });

        consultaproduto.setText("CONSULTAR PRODUTOS");
        consultaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaprodutoActionPerformed(evt);
            }
        });

        consultavenda.setText("CONSULTAR VENDAS");
        consultavenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultavendaActionPerformed(evt);
            }
        });

        RegistoVenda.setText("REGISTRAR VENDA");
        RegistoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistoVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastrofornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clientecadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastroproduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(consultaproduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultavenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(clientecadastro)
                .addGap(18, 18, 18)
                .addComponent(cadastroproduto)
                .addGap(18, 18, 18)
                .addComponent(cadastrofornecedor)
                .addGap(18, 18, 18)
                .addComponent(RegistoVenda)
                .addGap(18, 18, 18)
                .addComponent(consultaproduto)
                .addGap(18, 18, 18)
                .addComponent(consultavenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaprodutoActionPerformed
 
     if(tipo.equalsIgnoreCase("Gerente")){
         new ConsultaProdutos().setVisible(true);
     }
    }//GEN-LAST:event_consultaprodutoActionPerformed

    private void clientecadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientecadastroActionPerformed
 
         if(!tipo.equalsIgnoreCase("Financeiro")){
          new CadastroClientesTela().setVisible(true);
      }
    }//GEN-LAST:event_clientecadastroActionPerformed

    private void cadastroprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroprodutoActionPerformed
        
         if(!tipo.equalsIgnoreCase("Financeiro")){
            new CadastroDeProdutoTela().setVisible(true);
      }
    }//GEN-LAST:event_cadastroprodutoActionPerformed

    private void cadastrofornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrofornecedorActionPerformed
      
       if(!tipo.equalsIgnoreCase("Atendente")){
            new CadastroFornecedoresTela().setVisible(true);
       }
    }//GEN-LAST:event_cadastrofornecedorActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void consultavendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultavendaActionPerformed

        if(!tipo.equalsIgnoreCase("Atendente")){
            new ConsultaVendas().setVisible(true);
        }
    }//GEN-LAST:event_consultavendaActionPerformed

    private void RegistoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistoVendaActionPerformed
       if(!tipo.equalsIgnoreCase("Financeiro")){
           new RegistroVendasTela().setVisible(true);
       }
    }//GEN-LAST:event_RegistoVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain(tipo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistoVenda;
    private javax.swing.JButton cadastrofornecedor;
    private javax.swing.JButton cadastroproduto;
    private javax.swing.JButton clientecadastro;
    private javax.swing.JButton consultaproduto;
    private javax.swing.JButton consultavenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
